### ISSUE TITLE
Encontrar Proyecto en SICOES

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#1]
## Historia de Usuario
**COMO** EQUIPO
**QUIERO** obtener una idea de proyecto en SICOES
**PARA QUE** se pueda empezar a trabajar en ella para la materia.

## Criterio de Aceptacion
- [x] Subir una idea a la plataformavirtual

**Comment by camiloayza23** [comment]
Opciones encontradas:

1) https://www.infosicoes.com/servicio-de-actualizaciones-tecnologicas-y-visuales-para-la-pagina-web-wwwboliviatravel-para-promocionar-destinos-turisticos-lct245267.html

2) https://www.infosicoes.com/adquisicion-de-software-para-la-implementacion-del-sistema-modular-de-informacion-lct374971.html

3) https://www.infosicoes.com/servicio-de-correccion-de-examenesimpresion-de-stickersfotografias-de-los-postulantes-y-publicacion-de-resultados-en-la-web-del-curso-prefacultativo-gestion-2013-lct88439.html

**Comment by camiloayza23** [comment]
**Opcion tomada por el equipo:**

https://www.infosicoes.com/servicio-de-actualizaciones-tecnologicas-y-visuales-para-la-pagina-web-wwwboliviatravel-para-promocionar-destinos-turisticos-lct245267.html
