### ISSUE TITLE
Definir si el proyecto sera Mobile o Web

### ISSUE THREAD

**Issue by hrnn** [Dev-Eritas/Dev-Eritas#10]
... ...

**Comment by MarianaCarlo** [comment]
## User Story 

**COMO:** Equipo Dev-Eritas 
**QUIERO:** Realizar un proyecto que sea de tipo WEB
**PARA QUE:** Se cree un servicio para promocionar destinos turísticos de la página www.boliviatravel.com 

## Criterio de Aceptación
- [x] Tener una opción decidida

**Comment by TinCodes** [comment]
La consulta al equipo asignada a @TinCodes

**Comment by TinCodes** [comment]
Tras consultar al equipo se decidió realizar una plataforma web que sea responsiva (que se pueda visualizar mediante celular sin problemas)
