### ISSUE TITLE
Definir quienes usaran la applicación

### ISSUE THREAD

**Issue by hrnn** [Dev-Eritas/Dev-Eritas#11]

**Comment by MarianaCarlo** [comment]
## Historia de Usuario
**COMO:** Equipo Dev-Eritas
**QUEREMOS:** Definir quienes utilizarán la aplicación WEB
**PARA QUE:** Definamos a quienes nos dirigimos
## Criterios de aceptación
- [x] Para que la gente utilice la página WEB, el proyecto va dirigido al público en general pero en especial a la gente que esté interesado en destinos turísticos

**Comment by SaraUP** [comment]
Administradores y usuarios interesados en viajar
