### ISSUE TITLE
Definir tecnología front-end

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#12]
## Historia de usuario
**COMO:** Equipo Dev-Eritas
**QUIERO:** Escoger alguna tecnología para el avance de front-end
**PARA QUE:** Se tenga definido la herramienta y comenzar 

## Criterio de Aceptación
- [x] Tener definido la tecnología que será frontend cuando se este en la etapa de desarrollo

**Comment by TinCodes** [comment]
Investigacion acerca de tecnologias para Front-End y Back-End asignado a @MarianaCarlo

**Comment by MarianaCarlo** [comment]
Para las herramientas que se utilizarán en la parte de front-end será: HTML con CSS, en el camino se decidirá con el equipo si se utilizará Javascript
