### ISSUE TITLE
Definir tecnología back-end

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#13]
## Historia de usuario
**COMO:** Equipo Dev-Eritas
**QUEREMOS:** Definir alguna tecnología para comenzar el avance de back-end 
**PARA QUE:** Tengamos una idea definida que usar 

## Criterio de Aceptación
- [x] Tener definido la tecnología que se utilizará durante el desarrollo

**Comment by TinCodes** [comment]
Investigacion acerca de tecnologias para Front-End y Back-End asignado a @MarianaCarlo

**Comment by MarianaCarlo** [comment]
Con el equipo se decidió que se utilizará MySQL para referirse a la base de datos, además de utilizar PHP.
