### ISSUE TITLE
Investigacion acerca de CMS

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#14]
**Como** DevEritas
**Quiero** realizar una investigacion simple acerca de tecnologias para la realizacion de CMS's 
**Para que** podamos utilizar esas tecnologias en nuestras herramientas para desarrollar back-end

## Criterio de Aceptación
- [x] Tener una idea clara de lo que es y de lo que necesitamos para el proyecto

**Comment by TinCodes** [comment]
Asignado a @SaraUP

**Comment by SaraUP** [comment]
Un CMS (content management system) se compone basicamente de: 
varios ABM (alta, baja y/o modificación) del contenido, gestión 
de usuarios, autenticación y autorización, interacción con base 
de datos, entre otros.
Nuestro CMS al final deberá ser: intuitivo, flexible, seguro, etc...

Queremos que minimamente el cliente pueda cambiar el contenido de la página (como texto e imagenes).
