### ISSUE TITLE
Definir objetivos adicionales

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#15]
**Como** DevEritas
**Queremos** generar objetivos adicionales a la etapa de analisis
**Para que** podamos avanzar a objetivos de la etapa de diseño y continuar con el proyecto

## Criterio de Aceptación
- [x] Tener definido de manera clara todos los objetivos que sean adicionales a el proyecto

**Comment by TinCodes** [comment]
@hrnn perdon profe, nos trancamos en cuanto a conseguir nuevos objetivos para poder avanzar. Sera que nos puede ayudar?

**Comment by camiloayza23** [comment]
### OBJETIVO 

El objetivo del equipo "Dev-Eritas" es crear un CMS (Content Management System), sistema de gestión de contenidos, de forma que se pueda administrar contenido en la página www.boliviatravel.com. En este sentido se pretende que dicho sistema sea totalmente funcional, y se pueda eliminar, agregar y editar la información que se maneje en el Ministerio de Culturas y Turismo.

**Comment by camiloayza23** [comment]
Mas informacion en la wiki: https://github.com/Dev-Eritas/Dev-Eritas/wiki/2.-Descripci%C3%B3n-del-proyecto
