### ISSUE TITLE
Adicionar Requerimientos Generales a la wiki

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#16]
**Como** DevEritas
**Queremos** tener requerimientos generales documentados en la wiki
**Para que** se mantenga la documentacion del proyecto y se sigan los requerimientos necesarios para cumplir el proyecto

## Criterio de Aceptación
- [x] Tener en claro los requerimientos generales en la wiki, ya sea lo que tenga que ver con frontend y backend

**Comment by TinCodes** [comment]
Asignado a @camiloayza23

**Comment by camiloayza23** [comment]
https://github.com/Dev-Eritas/Dev-Eritas/wiki/2.-Documentaci%C3%B3n-sobre-el-proyecto
