### ISSUE TITLE
Crear Home wiki

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#18]
## Historia de usuario
**COMO:** Dev-Eritas
**QUIERO:** Que se tenga un orden de todo el contenido del proyecto
**PARA QUE:** Sea más visible la organización de la documentación

## Criterio de Aceptación
- [x] Tener creado "Home" para que se encuentre un indice de todo el contenido que tendrá la primera parte del proyecto

**Comment by camiloayza23** [comment]
Wiki organizada segun los criterios de evaluacion del primer termino de la materia, gracias @MarianaCarlo

**Comment by SaraUP** [comment]
Super
