### ISSUE TITLE
Diseño de interface en baja calidad

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#2]
MockUps

**Comment by MarianaCarlo** [comment]
Como: Dev-Eritas
Deseamos: Realizar mockups de baja calidad usando la herramienta balsamiq

**Comment by TinCodes** [comment]
Diseño de mockups de baja calidad asignado a @SaraUP

**Comment by MarianaCarlo** [comment]
Mockups finales que se realizaron en marvelapp
