### ISSUE TITLE
Crear mockups para la página

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#20]
## Historia de Usuario
**COMO:** Equipo Dev-Eritas
**QUIERO:** Crear el mockup de la pagina principal
**PARA QUE:** Definir como se vera la pagina principal en el website

## Criterio de Aceptación
- [x] Tener todos los mockups de la aplicación terminados, incluyendo los de la interfaz de usuario y los correspondientes a los casos de uso

**Comment by MarianaCarlo** [comment]
Los mockups son sencillos de entender ya que tanto para los usuarios y los administradores la interfaz que se muestra es similar

**Comment by SaraUP** [comment]
Son de baja interfaz
