### ISSUE TITLE
Realizar Poker Planning

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#22]
## User Story
**COMO:** Equipo Dev-Eritas
**QUIERO:** Realizar la metodología de Poker Planning
**PARA QUE:** Definir cuanto tiempo y esfuerzo tomará cada una de las tareas

## Criterio de Aceptación 
- [x] Labels con estimaciones creadas y user stories con sus respectivas estimaciones

**Comment by TinCodes** [comment]
Se utilizo el Poker Planning para poder estimar los User Stories existentes.
Consecuentes User Stories seran estimados de la misma manera.
https://play.planningpoker.com/play/game/0DFqFIPd60kQ938g82FMGPUhfnc816H1

**Comment by TinCodes** [comment]
Todos los objetivos de este sprint han sido cumplidos, no se necesita mas poker planning.
