### ISSUE TITLE
Casos de uso - Seleccionar Idioma

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#27]
## Historia de usuario
**COMO:** Dev-Eritas
**QUIERO:** Que la página ofrezca a los usuarios la pagina en diferentes idiomas
**PARA QUE:** Esta pagina no esté restringida a un único idioma

## Criterio de Aceptación
- [x] Tener el diagrama del caso de uso (correspondiente también a los mockups) que describe la actividad

**Comment by camiloayza23** [comment]
Esta opcion esta super, pero puede ser un poco complicada

**Comment by MarianaCarlo** [comment]
Esta acción será un poco complicado por lo que se tendrá que ver los idiomas que se tendrá y que no altere la información que se tenga en el idioma original cuando el usuario quiera cambiarlo
