### ISSUE TITLE
Documentación sobre proyecto elegido

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#3]
**Como** Dev-Eritas
**Deseamos** escribir una wiki que describa las funcionalidades del proyecto de SICOES previamente elegido
**Para que** podamos entenderlo mejor

## Criterio de Aceptación
- [x] La Wiki debe estar completa y se deben enteder todos los puntos del proyecto elegido

**Comment by TinCodes** [comment]
Asignado a @camiloayza23 
Probablemente este User Story sea repetido 
- [ ] Borrarlo/Cambiar de nombre/Modificarlo

**Comment by camiloayza23** [comment]
https://github.com/Dev-Eritas/Dev-Eritas/wiki/2.-Documentaci%C3%B3n-sobre-el-proyecto
