### ISSUE TITLE
Desarrollo del proyecto

### ISSUE THREAD

**Issue by SaraUP** [Dev-Eritas/Dev-Eritas#38]
## Historia de Usuario
**COMO**: Dev-Eritas
**QUIERO**: Empezar a codear 
**PARA QUE**: No se retrasé el proyecto

## Criterio de Aceptación
- [x] Empezar con lo principal del desarrollo del proyecto

**Comment by camiloayza23** [comment]
**MUY** probablamente por tiempo esto pase al siguiente sprint

**Comment by MarianaCarlo** [comment]
Esta parte la podríamos comenzar con lo más básico, comenzado con el frontend para luego ya enlazar el backend

**Comment by camiloayza23** [comment]
![image](https://user-images.githubusercontent.com/37802680/70847628-da720d00-1e3c-11ea-92f2-1893fce835d3.png)

**Comment by camiloayza23** [comment]
Necesita revision pero se avanzo bastante en el desarrollo
