### ISSUE TITLE
Crear una Wiki para guiarnos con labels

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#4]
**Como** Dev-Eritas
**Quiero** Crear una wiki que contenga los labels usados en cada tarea, para hacer mas facil el manejo del backlog a lo largo del proyecto
**Para** Poder entender y mantener organizados a lo largo del proyecto todos los labels utilizados

Criterios de Aceptación:
- [x]  La wiki cuenta con las labels creadas
- [x]  Se encuentra en un formato facil de entender

**Comment by TinCodes** [comment]
Mantenimiento de la wiki asignado a @camiloayza23 

- [ ] Cambiar el titulo del User Story

**Comment by camiloayza23** [comment]
Wiki sobre labels creada.
