### ISSUE TITLE
Definir nuevas labels

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#40]
## Historia de Usuario
**COMO:** Dev-Eritas
**QUIERO:** Tener ordenado y tener claro las labels que se usaran en el sprint 2
**PARA QUE:** esté mas organizado el documento

## Criterio de Aceptación
- [x] Definir las nuevas labels y tenerlo registrado en la wiki

**Comment by camiloayza23** [comment]
**Nuevas labes en la documentacion de Wiki** 
https://github.com/Dev-Eritas/Dev-Eritas/labels

**Comment by camiloayza23** [comment]
**NOTAS**
El nuevo label para esta semana es **sprint2**, seguimos en la **primera parte**
Se mantienen todos los labels previos para el poker planning
NO OLVIDAR separar por front-end y back-end
