### ISSUE TITLE
Definir el modelo de la BDD

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#41]
## Historia de Usuario
**COMO:** Dev-Eritas
**QUIERO:** Definir el modelo entidad-relación de la base de datos
**PARA QUE:** Se pueda desarrollar la base da datos de forma eficiente

## Criterio de Aceptación
- [ ] Tener acordado con los integrantes del equipo sobre el modelo de la base de datos que realizaremos

**Comment by camiloayza23** [comment]
Herramienta que sera usada: https://dbdiagram.io/

**Comment by MarianaCarlo** [comment]
Es necesario definir el modelo para que en el desarrollo no tengamos problemas

**Comment by camiloayza23** [comment]
![WhatsApp Image 2019-12-02 at 08 12 12](https://user-images.githubusercontent.com/37802680/69958694-c0027000-14db-11ea-8b25-192d75bbeadf.jpeg)

**Primer borrador del diseño**

**Comment by SaraUP** [comment]
Ejemplo de organización de la BD: https://xmeele.wordpress.com/2009/07/23/creacion-de-un-cms-la-base-de-datos/

**Comment by camiloayza23** [comment]
[Untitled.pdf](https://github.com/Dev-Eritas/Dev-Eritas/files/3937426/Untitled.pdf)

Archivo de modelo de BDD
