### ISSUE TITLE
Crear carpetas para el desarrollo

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#42]
## Historia de Usuario

**COMO:** Dev-Eritas
**QUIERO:** Crear carpetas para el desarrollo del proyecto
**PARA QUE:** Se pueda desarrollar el proyecto de manera óptima

## Criterio de Aceptación
- [x] Tener acordado las carpetas que tendrá el proyecto en el transcurso del desarrollo

**Comment by camiloayza23** [comment]
Las carpetas van a relación a las funciones y frameworks que decidió el equipo por lo tanto las carpetas aún no han sido creadas

**Comment by TinCodes** [comment]
Para poder tener un inicio ordenado se crearon 3 carpetas (html, css, js) a modo de tener los archivos que se vayan a crear en sus respectivas carpetas.

**Comment by TinCodes** [comment]
Aun puede cambiar radicalmente la estructura de las carpetas a medida que el equipo vea conveniente, este es solo un inicio.
