### ISSUE TITLE
[Opcional] Investigar acerca de Laravel

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#45]
## Historia de Usuario
**COMO:** Equipo Dev-Eritas
**QUIERO:**  Determinar la información de Laravel
**PARA QUE:** Podamos considerarlo en el proyecto

### Criterios de aceptación

- [x] Subir la información a la wiki

**Comment by camiloayza23** [comment]
Información más a fonde se encontrará en la Wiki: https://github.com/Dev-Eritas/Dev-Eritas/wiki/%5BGuide%5D-Investigaciones

**Comment by camiloayza23** [comment]
Laravel es un framework PHP. Es uno de los frameworks más utilizados y de mayor comunidad en el mundo de Internet.

Como framework resulta bastante moderno y ofrece muchas utilidades potentes a los desarrolladores, que permiten agilizar el desarrollo de las aplicaciones web.

MANUAL: https://desarrolloweb.com/manuales/manual-laravel-5.html
