### ISSUE TITLE
[Opcional] Investigar acerca de JHipster 

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#46]
## Historia de Usuario
**COMO:** Equipo Dev-Eritas
**QUIERO:**  Determinar la información de JHipster 
**PARA QUE:** Podamos considerarlo en el proyecto

### Criterios de aceptación

- [x] Subir la información a la wiki

**Comment by MarianaCarlo** [comment]
JHipster proporciona herramientas para generar un proyecto con una pila Java en el lado del servidor (usando Spring Boot) y un front-end web receptivo en el lado del cliente (con Angular y Bootstrap ). También puede crear una pila de microservicios con soporte para Netflix OSS, Docker y Kubernetes.

**Comment by SaraUP** [comment]
Es una herramienta super interesante
