### ISSUE TITLE
[Opcional] Investigar acerca de React

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#47]
## Historia de Usuario
**COMO:** Equipo Dev-Eritas
**QUIERO:**  Determinar la información de React
**PARA QUE:** Podamos considerarlo en el proyecto

### Criterios de aceptación

- [x] Subir la información a la wiki

**Comment by MarianaCarlo** [comment]
React nos ayuda a construir las aplicaciones que usan datos que cambian todo el tiempo, esto
serviría para el proyecto ya que habrá mucho flujo de cambios por parte del administrador
donde modificará, editará y eliminará el contenido de la página

**Comment by MarianaCarlo** [comment]
Algunos ejemplos que son básicos: https://reactjsexample.com/a-very-simple-resizable-panel-as-a-react-component/

**Comment by MarianaCarlo** [comment]
React tutorial básico: crear proyecto react y correr el proyecto:
https://www.w3schools.com/react/
