### ISSUE TITLE
Realizar Poker Planning 

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#48]
## Historia de Usuario
**COMO:** Equipo Dev-Eritas
**QUIERO:** Realizar la metodología de Poker Planning
**PARA QUE:** Definir cuanto tiempo y esfuerzo tomará cada una de las tareas

## Criterio de Aceptación
- [x] Tener acordado con los integrantes del equipo sobre las estimaciones de las diferentes tareas que se tiene

**Comment by MarianaCarlo** [comment]
Realizar esta acción es muy útil porque se discute las estimaciones de cada tarea especifica con los integrantes

**Comment by MarianaCarlo** [comment]
Cuando creamos un issue, todos los integrantes realizamos la actividad del poker planning para discutir las estimaciones
