### ISSUE TITLE
Crear diseño para Bolivia Travel

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#49]
## Historia de Usuario
**COMO:** Equipo Dev-Eritas
**QUIERO:** Crear diseño para Bolivia Travel
**PARA QUE:** Este figure en la página web www.boliviatravel.com

## Criterio de Aceptación
- [x] Tener definido el diseño de lo que es el logo de la pagina web

**Comment by camiloayza23** [comment]
![tespera-1](https://user-images.githubusercontent.com/37802680/69803776-6d5f4600-11b3-11ea-953f-1c9c376fd452.jpg)

**OPCIÓN 1**

**Comment by camiloayza23** [comment]
![opcion2](https://user-images.githubusercontent.com/37802680/69804049-10b05b00-11b4-11ea-8fb8-d5492b8d227d.jpg)

**OPCIÓN 2**

**Comment by MarianaCarlo** [comment]
Me gusta el primer diseño porque en las letras de "BOLIVIA" hay un diseño característico
