### ISSUE TITLE
Diseño de arquitectura de Proyecto

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#5]

**Comment by MarianaCarlo** [comment]
## Historia de Usuario
**COMO:** Equipo Dev-Eritas
**QUEREMOS:** Tener definido el diseño de arquitectura
**PARA QUE:** Empecemos con una herramienta ya acordada entre todos la cual puede ser: draw.io

## Criterio de Aceptación
- [x] Diagrama general de la arquitectura

**Comment by TinCodes** [comment]
@hrnn aun existen dudas de como decidir la arquitectura para este tipo de proyecto, pensabamos tal vez en cliente-servidor pero no es seguro.

**Comment by TinCodes** [comment]
La arquitectura basica del proyecto ha sido completada utilizando draw.io.
