### ISSUE TITLE
[Opcional] Investigar acerca Angular

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#51]
## Historia de Usuario
**COMO:** Equipo Dev-Eritas
**QUIERO:**  Determinar la información de Angular
**PARA QUE:** Podamos considerarlo en el proyecto

### Criterios de aceptación

- [x] Subir la información a la wiki

**Comment by camiloayza23** [comment]
Local setup for Angular: https://angular.io/guide/setup-local
Informacion interesante: https://sg.com.mx/revista/56/angular

**Comment by camiloayza23** [comment]
Se organizara mejor la informacion en una wiki
https://github.com/Dev-Eritas/Dev-Eritas/wiki/%5BGuide%5D-Investigaciones

**Comment by camiloayza23** [comment]
Investigacion terminada
