### ISSUE TITLE
Implementación de flujos

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#53]
**COMO:** Equipo Dev-Eritas
**QUIERO:** Implementar el flujo de la página previamente creado
**PARA QUE:** La página se encuentre organizada de la forma en la que se pensó

### Criterios de aceptación

- [x] Se sigue el flujo de la página

**Comment by camiloayza23** [comment]
Se sufre algunos problemas por el manejo de links de Laravel **SOLUCIONAR**

**Comment by SaraUP** [comment]
Cuales son los links con problemas?
