### ISSUE TITLE
Formularios completos (CRUD)

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#54]
**COMO:** Equipo Dev-Eritas
**QUIERO:** Crear formulario completos
**PARA QUE:** Se pueda manejar sin problemas los formularios de la página web
### Criterios de aceptación
- [x] Create
- [x] Read
- [x] Update 
- [x] Delete

**Comment by camiloayza23** [comment]
No se cuenta con una interfaz grafica para esto, pero se lo puede hacer

**Comment by camiloayza23** [comment]
**NOTIFICAR** phpmyadmin permite realizar los cambios por la forma en la que la BDD esta hecha

**Comment by SaraUP** [comment]
Podriamos hacer la interfaz para el Sprint 5
