### ISSUE TITLE
Crear la pagina de login

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#55]
**COMO** [algun rol]
**QUIERO** tener una manera de autenticarme en la pagina del proyeto
**PARA QUE** pueda tener una vista y funcionalidades especificas a mi rol

- [x] Tener una idea de autenticar usuarios
- [x] Distinguir roles y permisos
- [x] Tener una pagina funcional de login

**Comment by MarianaCarlo** [comment]
Se tiene ya el login donde se tiene autenticacion de correo y contraseña

**Comment by SaraUP** [comment]
Eso quedo super bien!
