### ISSUE TITLE
Manejo del proyecto

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#57]
**COMO:** Equipo Dev-Eritas
**QUIERO:** Documentar el manejo del proyecto
**PARA QUE:** El manejo del proyecto se encuentre organizado y se vuelva más sencillo

### Criterios de aceptación
- [x] Issues
- [x] Estimación
- [x] Kanban Board
- [x] Pull Request
- [x] Code Reviews

**Comment by camiloayza23** [comment]
Hacer comentarios en todos los issues, poniendo al dia a los miembros del equipo

**Comment by camiloayza23** [comment]
DEMOSTRACION DE SWAGGER

![Capture2](https://user-images.githubusercontent.com/37802680/70847715-ead6b780-1e3d-11ea-89cb-65c686a80106.PNG)

**Comment by SaraUP** [comment]
Excelente
