### ISSUE TITLE
Clonar el codigo del repositorio

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#58]
## User Story
**COMO** cada miembro del equipo DevEritas
**QUIERO** clonar a mi repositorio local el contenido inicial del repositirio remoto
**PARA QUE** pueda tener un ambiente de trabajo listo para desarrollar

## Criterio de Aceptacion
- [x] Repositorio Local funcionando (@MarianaCarlo )
- [x] Repositorio Local funcionando (@SaraUP )
- [x] Repositorio Local funcionando (@camiloayza23 )
- [x] Repositorio Local funcionando (@TinCodes )

**Comment by TinCodes** [comment]
Por ahora lo que contiene el repo son solamente las carpetas genericas que pueden cambiar despues, pero es principalmente para tener un inicio.

**Comment by TinCodes** [comment]
Utilicen este comando estando en la carpeta donde quieren hacer su repo local:
$ git clone https://github.com/Dev-Eritas/Dev-Eritas.git

Refresquen su memoria con los comandos git, este video me ayudo a mi: 
https://www.youtube.com/watch?v=0fKg7e37bQE

**Comment by MarianaCarlo** [comment]
Ya esta

**Comment by camiloayza23** [comment]
Para Visual Studio > Realizar un git clone y entrar a la carpeta, Visual Studio reconocera esta accion automaticamente. PRIMERO hacer un pull luego se pueden manejar los cambios comodamente.
