### ISSUE TITLE
Crear la pagina del Admin

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#60]
## User Story

**COMO** Administrador del CMS
**QUIERO** tener una pagina propia
**PARA QUE** pueda editar usuarios, editar las paginas, editar los contenidos y visualizar estadisticas de visitas y otros datos.

## Criterio de Aceptacion
- [x] Admin debe poder hacer login
- [x] Tener creado el dashboard con HTML y CSS
- [x] Tener el CRUD de usuarios
- [x] Tener el CRUD de contenido
- [x] Tener el CRUD de paginas
- [x] Crear estadisticas visualizables

**Comment by MarianaCarlo** [comment]
Se creo la pagina de admin, su home es que le muestre el dashboard con todo lo que puede hacer

**Comment by SaraUP** [comment]
Perfecto
