### ISSUE TITLE
Definir modelos de los templates

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#61]
##User Story

**COMO** DevEritas
**QUIERO** distinguir varios tipos de paginas genericas
**PARA QUE** se pueda crear con facilidad la estructura del sitio web con el CMS.

##Criterio de Aceptacion
- [x] Tener una lista de los diferentes templates
- [x] Documentar los templates

**Comment by SaraUP** [comment]
**Se encontraron 10 tipos de templates diferentes**

TIPO 1:

![tespera-1](https://cdn.discordapp.com/attachments/235901789948477441/651108755840172132/9.jpg)

TIPO 2:

![tespera-1](https://cdn.discordapp.com/attachments/235901789948477441/651108758713401365/10.jpg)

TIPO 3:

![tespera-1](https://cdn.discordapp.com/attachments/235901789948477441/651108734323523595/7.jpg)

TIPO 4:

![tespera-1](https://cdn.discordapp.com/attachments/235901789948477441/651108730309574666/5.jpg)

TIPO 5:

![tespera-1](https://cdn.discordapp.com/attachments/235901789948477441/651108729625903104/21.jpg)

TIPO 6:

![tespera-1](https://cdn.discordapp.com/attachments/235901789948477441/651108727981735977/20.jpg)

TIPO 7:

![tespera-1](https://cdn.discordapp.com/attachments/235901789948477441/651108664710660098/4.jpg)

TIPO 8:

![tespera-1](https://media.discordapp.net/attachments/235901789948477441/651108041625829398/unknown.png?width=654&height=473)

TIPO 9:

![tespera-1](https://cdn.discordapp.com/attachments/235901789948477441/651109274319061012/8.jpg)

TIPO 10:

![tespera-1](https://cdn.discordapp.com/attachments/235901789948477441/651108760869273610/11.jpg)

**Comment by MarianaCarlo** [comment]
Los 10 tipos definidos de templates esta bien, nos ayudan a no tener muchas pantallas

**Comment by camiloayza23** [comment]
El modelo esta buenisimo!
