### ISSUE TITLE
Desarrollar los templates definidos

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#62]
## User Story

**COMO** DevEritas
**QUIERO** tener el codigo 
**PARA QUE** pueda editar usuarios, editar las paginas, editar los contenidos y visualizar estadisticas de visitas y otros datos.

## Criterio de Aceptacion
- [ ] Tener los archivos en el master

**Comment by MarianaCarlo** [comment]
Ya se acabo lo de los templates de la parte del usuario que solo verá el contenido y los templates del administrador

**Comment by SaraUP** [comment]
Perfecto
