### ISSUE TITLE
Investigar acerca de WYSIWYG (editores de texto)

### ISSUE THREAD

**Issue by SaraUP** [Dev-Eritas/Dev-Eritas#63]
## User Story
**COMO**: Equipo
**QUIERO**: investigar acerca de editores de texto
**PARA QUE**: se lo utilice en nueztro CMS

## Criterio de Aceptación:
- [ ] Definir que tipo de editor se hará para el proyecto (sencillo)

**Comment by SaraUP** [comment]
WYSIWYG, acrónimo de What You See Is What You Get, es aplicado a los procesadores de texto y otros editores de texto con formato, que permiten escribir un documento mostrando directamente el resultado final, frecuentemente el resultado impreso. En el caso de editores de HTML, este concepto se aplica a los que permiten escribir la página sobre una vista preliminar similar a la de un procesador de textos, ocupándose en este caso el programa de generar el código fuente en HTML. Se utiliza en contraposición a otros procesadores de texto, hoy en día poco frecuentes, en los que se escribía sobre una vista que no mostraba el formato del texto, hasta la impresión del documento.

**Comment by MarianaCarlo** [comment]
Encontre varios ejemplos de WYSIWYG:
* https://summernote.org/
* https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg
* https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/overview.html#compatibility-with-bootstrap

**Comment by MarianaCarlo** [comment]
Este tiene templates que son simples:
* https://ckeditor.com/
