### ISSUE TITLE
Crear el WYSIWYG

### ISSUE THREAD

**Issue by SaraUP** [Dev-Eritas/Dev-Eritas#64]
## User Story

**COMO** Equipo
**QUIERO** crear un buen editor de texto
**PARA QUE** el administrador pueda cambiar detalles del contenido de las páginas

## Criterio de Aceptacion
- [ ] Funcional
- [ ] Sencillo
- [ ] Intuitivo

**Comment by MarianaCarlo** [comment]
Cree el editor de texto que es "ckeditor", cree una branch para que lo vean en Dev-Elopment

**Comment by camiloayza23** [comment]
Excelente editor!
