### ISSUE TITLE
Crear el header y footer para la pagina

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#66]
## User Story

**COMO** DevEritas
**QUIERO** crear archivos HTML y CSS para el header y footer
**PARA QUE** se puedan implementar en todas las paginas

## Criterio de Aceptacion
- [x] Codigo HTML y CSS en algun branch.
- [ ] Codigo merged en el master.

**Comment by MarianaCarlo** [comment]
Cree un branch que es index para que ahi este la base de header y footer, no hice todavia merge solo el pull request

**Comment by MarianaCarlo** [comment]
En la parte del footer puse 3 iconos (instagram,facebook, twitter) para que se los redireccione las páginas
