### ISSUE TITLE
Crear carpetas de desarrollo en Dev-Elopment

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#69]
## User Story

**COMO** Dev-Eritas
**QUIERO** Mover las carpetas de desarrollo al nuevo repositorio
**PARA QUE** Se mantenga organizado el github

## Criterio de Aceptacion
- [x] Tener las carpetas en Dev-Elopment

**Comment by camiloayza23** [comment]
Carpetas básicas creadas: https://github.com/Dev-Eritas/Dev-Elopment

**Comment by SaraUP** [comment]
SUPER
