### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by SaraUP** [Dev-Eritas/Dev-Eritas#7]
**COMO**: Equipo Dev-Eritas
**QUIERO**: Empezar a ver como se va a hacer la aplicación web
**PARA QUE**: Se tenga definido la pinta de la página

**Comment by SaraUP** [comment]
Mockups

**Comment by TinCodes** [comment]
Mockups asignados a Sara

**Comment by SaraUP** [comment]
Mockups de baja calidad terminados: https://marvelapp.com/7jgh681/screen/63974727
