### ISSUE TITLE
Crear login en laravel

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#72]
## User Story

**COMO** Dev-Eritas
**QUIERO** Crear un login usando laravel
**PARA QUE** Se cuente con un fácil sistema de login

## Criterio de Aceptacion
- [x] Los usuarios pueden entrar a la plataforma

**Comment by TinCodes** [comment]
Estoy incluyendo un paquete para poder implementar un login simple que podamos utilizar, se llama Laravel UI.

**Comment by camiloayza23** [comment]
Se puede realizar un login gracias a esa tecnologia.
