### ISSUE TITLE
Probar templates en laravel

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#73]
## User Story

**COMO** Dev-Eritas 
**QUIERO** Probar el flujo en laravel
**PARA QUE** Completar el buen funcionamiento del flujo

## Criterio de Aceptacion
- [ ] Que el flujo de la página tenga sentido

**Comment by TinCodes** [comment]
Mediante los controllers y views estoy viendo si puedo generar ciertos templates con Orientacion a Objetos

**Comment by SaraUP** [comment]
Super
