### ISSUE TITLE
Añadir las carpetas de laravel al repositorio

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#74]
## User Story

**COMO** Dev-Eritas
**QUIERO** Subir las carpetas de Laravel al repositorio
**PARA QUE** El proyecto se mantenga actualizado

## Criterio de Aceptacion
- [x] Las carpetas deben estar en Dev-Elopment

**Comment by camiloayza23** [comment]
Todas las carpetas que funcionan correctamente se encuentran en la branch LaravelSwagger

**Comment by MarianaCarlo** [comment]
Esa branch ya está mas ordenada
