### ISSUE TITLE
Pasar CSS y HTML a Laravel

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#75]
## User Story

**COMO** Dev-Eritas
**QUIERO** Mover los archos de CSS y HTML a las carpetas de Laravel
**PARA QUE** Estos archivos se incorporen a la estructura de Laravel

## Criterio de Aceptacion
- [x] Los archivos deben estar en las carpetas
- [x] El flujo se debe mantener

**Comment by MarianaCarlo** [comment]
Los archivos ya se pasaron a laravel y se convirtió todos los css a ua sola carpeta, lo mismo con carpeta js

**Comment by SaraUP** [comment]
Super bien!
