### ISSUE TITLE
Crear BD en Laravel

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#77]
## User Story

**COMO** Dev-Eritas 
**QUIERO** Crear la BD en Laravel
**PARA QUE** Pueda ser utilizada en toda la aplicación

## Criterio de Aceptacion
- [x] La BD cuenta con los campos necesarios y además se puede usar en la aplicación

**Comment by camiloayza23** [comment]
La base de datos ha sido creada y el modelo se encuentra en la Wiki

**Comment by SaraUP** [comment]
Perfecto
