### ISSUE TITLE
Pasar todo lo del frontend a laravel

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#79]
## User Story

**COMO** Equipo Dev-Eritas
**QUIERO** Pasar lo que se hizo de frontend en bootstrap a laravel 
**PARA QUE** Se tenga todo organizado en laravel

## Criterio de Aceptacion
- [x] Todos los archivos de css que esten si o si en uno solo
- [x] Todo los archivos html converetirlos a php

**Comment by MarianaCarlo** [comment]
Ya se hizo push en la branch LaravelSwagger con todas las paginas y css,js,img,videos,etc

**Comment by SaraUP** [comment]
Se ve super bien!
