### ISSUE TITLE
Crear la pagina principal de la Wiki

### ISSUE THREAD

**Issue by hrnn** [Dev-Eritas/Dev-Eritas#8]
**COMO** EQUIPO
**QUIERO** tener el objetivo principal
**PARA QUE** se tenga claro el proyecto.

## Criterio de Aceptacion
- [x] La página debe tener el objetivo principal de lo que se busca con el proyecto

**Comment by TinCodes** [comment]
Asignado a @MarianaCarlo

**Comment by MarianaCarlo** [comment]
Se creó la página de Wiki para que se empiece la documentación
