### ISSUE TITLE
Investigar acerca de blade (Laravel)

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#80]
## User Story

**COMO** Equipo Dev-Eritas
**QUIERO** Saber mas sobre el funcionamiento de blade
**PARA QUE** No tengamos problemas en Laravel

## Criterio de Aceptacion
- [ ] Tener en claro todo lo que puede hacer blade y en que nos beneficia

**Comment by TinCodes** [comment]
Blade parece estar muy bueno para poder simplificar y ahorrarnos codigo, ademas de hacer que las paginas tengan contenido dinamico. Seguire viendo acerca de eso. @camiloayza23 te lo explico, te va a gustar

**Comment by SaraUP** [comment]
Hay que seguir investigando
