### ISSUE TITLE
Migraciones de BDs en Laravel

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#81]
## User Story

**COMO** DevEritas
**QUIERO** poder migrar una base de datos entre los integrantes del grupo
**PARA QUE** podamos mantener los mismos datos mientras trabajamos en Laravel

## Criterio de Aceptacion
- [X] Investigacion completada acerca de migraciones en Laravel
- [x] Migracion exitosa por medio del branch Laravel entre el equipo
- [ ] Implementacion de los archivos de migracion en el `master`

**Comment by TinCodes** [comment]
Estaba viendo que Laravel crea archivos de migracion por medio del comando `php artisan make:migration [filename]` y es bastante simple.

**Comment by TinCodes** [comment]
La conexion a la BD la hace Laravel automaticamente por medio del archivo `.env` donde existen las variables de DB_VARIABLE.

**Comment by TinCodes** [comment]
Los archivos de migracion son como scripts o instrucciones que se le da a la base de datos para que se puedan crear tablas y llenar de cosas, se utilizan mediante objetos y un metodo `up()` que realiza las instrucciones y un metodo `down()` que hace drop de las instrucciones del `up()`.

**Comment by camiloayza23** [comment]
![BDD](https://user-images.githubusercontent.com/37802680/70768104-1f614b00-1d3a-11ea-92bb-f638c49b3e40.png)
