### ISSUE TITLE
Actualizar los casos de uso

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#82]
## User Story

**COMO** Dev-Eritas
**QUIERO** Que se tenga la actualizacion de los casos de uso
**PARA QUE** Coincida con lo que se tiene avanzado

## Criterio de Aceptacion
- [x] Borrar los casos de uso que no se utilizaron
- [x] Modificar los casos de uso que se adapten a lo avanzado del proyecto

**Comment by camiloayza23** [comment]
**NO OLVIDAR** Los casos de uso tienen que estar en la wiki

**Comment by SaraUP** [comment]
Quedaron muy bien!
