### ISSUE TITLE
Crear Routes para los views

### ISSUE THREAD

**Issue by TinCodes** [Dev-Eritas/Dev-Eritas#83]
## User Story

**COMO** Dev Eritas
**QUIERO** crear Routes
**PARA QUE** todos los views sean encaminados para la navegacion de la pagina

## Criterio de Aceptacion
- [x] Routes creados

**Comment by TinCodes** [comment]
Porfa diganme que sitios tiene la pagina para que pueda crear sus routes.
(listenmelos porfa)

**Comment by MarianaCarlo** [comment]
/actualizaInfo
/adminHome
/blog
/ciudad
/contactos
/contactosDev
/eventosCulturales
/experiencias
/hoteles
/hotelSalar1
/hotelSalar2
/hotelSalar3
/welcome (es el index que es la pagina principal)
/login
/patrimonio
/perfil
/registrarAdmin
/sobreBolivia

**Comment by TinCodes** [comment]
Routes creados para la navegacion de la pagina
