### ISSUE TITLE
Diagrama de Secuencia - Editar contenido

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#84]
## User Story

**COMO** Administrador
**QUIERO** editar contenido
**PARA QUE** se actualice la información

## Criterio de Aceptacion
- [x] Tener en claro que cosas se puede editar

**Comment by MarianaCarlo** [comment]
El editar contenido solo le aparece al administrador en paginas especificas

**Comment by SaraUP** [comment]
YEY
