### ISSUE TITLE
Diagrama de Secuencia - Login

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#85]
## User Story

**COMO** Administrador
**QUIERO** ingresar a la pagina
**PARA QUE** pueda editar y ver su informacion como administrador

## Criterio de Aceptacion
- [x] Tener una contraseña y agun nombre de usuario que entre a la página

**Comment by MarianaCarlo** [comment]
![diagrama](https://cdn.discordapp.com/attachments/616111992490557450/655174871885545473/unknown.png)

**Comment by SaraUP** [comment]
Esta super
