### ISSUE TITLE
Poker Planning

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#87]
## User Story

**COMO** Equipo Dev-Eritas
**QUIERO** Tener una estimación de todas las tareas
**PARA QUE** estas estén organizadas

## Criterio de Aceptacion
- [x] Se toma estimaciones de tallas XS,S,M,L,XL,XXL

**Comment by camiloayza23** [comment]
El equipo realizo el poker planning para este sprint exitosamente

**Comment by SaraUP** [comment]
Los criterios son buenos!
