### ISSUE TITLE
Creación de usuarios

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#88]
## User Story

**COMO** Equipo Dev-Eritas
**QUIERO** crear varios usuarios
**PARA QUE** estos se guarden en una base de datos

## Criterio de Aceptacion
- [x] Cuando se cree un nuevo usuario, se tiene que agregar en la base de datos

**Comment by camiloayza23** [comment]
La base de datos con los usuarios ya funciona, yay

**Comment by SaraUP** [comment]
Yey
