### ISSUE TITLE
Arreglar errores de la aplicación web

### ISSUE THREAD

**Issue by SaraUP** [Dev-Eritas/Dev-Eritas#89]
## User Story

**COMO**: Grupo
**QUIERO**: Corregir todos los errores encontrados en la revisión del proyecto
**PARA QUE**: la aplicación funcione a la perfección 

## Criterio de Aceptacion
- [ ] No existen errores identificados anteriormente

**Comment by MarianaCarlo** [comment]
Ya se arregló los errores presentados en la segunda revisión, ahora solo queda ver lo del editor

**Comment by SaraUP** [comment]
Perfecto!!!!!!

**Comment by TinCodes** [comment]
Los errores causados por las identaciones y los tags que faltaban han sido corregidos
