### ISSUE TITLE
Seleccionar la herramienta para los mockups

### ISSUE THREAD

**Issue by hrnn** [Dev-Eritas/Dev-Eritas#9]
... ...

**Comment by MarianaCarlo** [comment]
## Historia de Usuario
**COMO:** Equipo Dev-Eritas
**QUEREMOS:** Tener seleccionado la herramienta que utilizaremos para los MockUps
**PARA QUE:** Se logre empezar a realizar el diseño, la herramienta será BALSAMIQ

## Criterio de Aceptación
- [x] La herramienta debe ser simple y facil de usar

**Comment by TinCodes** [comment]
Asignado a @SaraUP

**Comment by SaraUP** [comment]
Se cambio la herramienta a Marvel
