### ISSUE TITLE
Integración Continua con Github Actions

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#90]
## User Story

**COMO** Equipo Dev-Eritas
**QUIERO** crear integración continua (compilación o empaquetado)
**PARA QUE** Se pueda detecta errores más rápido y reduce la cantidad de código

## Criterio de Aceptacion
- [x] Compilacióno empaquetado
- [x] Testeo o verificación

**Comment by camiloayza23** [comment]
Se crearon 3 diferentes archivos de CI

- CI para front-end que compila de SCSS a CSS
- CI que realiza testing de Back-End con PHP Unit
- CI para back end que compila los archivos de todas las paginas blade.php

**Comment by camiloayza23** [comment]
El archivo node-sass no puede ser instalado en la maquina virtual ubuntu, buscando soluciones.

**Comment by camiloayza23** [comment]
Posible solución: https://github.com/sass/node-sass/issues/2475

**Comment by camiloayza23** [comment]
Problema solucionado!
