### ISSUE TITLE
Header correctamente usado para Administradores y Visionarios

### ISSUE THREAD

**Issue by MarianaCarlo** [Dev-Eritas/Dev-Eritas#91]
## User Story

**COMO** Equipo Dev-Eritas
**QUIERO** Que se muestre el header indicado
**PARA QUE** cada tipo tipo de usuario lo vea, no son iguales

## Criterio de Aceptacion
- [x] Navbar que tenga Home, Sobre Bolivia, Experiencias, Contactos

**Comment by MarianaCarlo** [comment]
@camiloayza23  @SaraUP  @TinCodes Hagan pull al branch de LaravelSwagger para tener esta partecita cambiada

**Comment by SaraUP** [comment]
Ya esta!!
