### ISSUE TITLE
Terminar blogs en la página

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#93]
## User Story

**COMO** Dev Eritas
**QUIERO** Terminar la aplicacion de blogs en la página 
**PARA QUE** Se pueda terminar la aplicacion de esta funcionalidad en la página

## Criterio de Aceptacion
- [x] Que los blogs se añadan y sean jalados desde la BDD
- [ ] Tener el editor de texto que añada datos a la BDD

**Comment by SaraUP** [comment]
Cuantos blogs?

**Comment by TinCodes** [comment]
Los blogs los podemos manejar tranquilamente con la base de datos, creo que ya veremos la cantidad

**Comment by TinCodes** [comment]
Los blogs se manejan bien usando el AdminController, se recuperan y se guardan. Listo!
