### ISSUE TITLE
Terminar el front-end de la página de Blogs

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#94]
## User Story

**COMO** Dev-Eritas
**QUIERO** Terminar el front-end de la página de Blogs
**PARA QUE** Se proceda a darle todas las funcionalidades que necesite

## Criterio de Aceptacion
- [ ] La página cuente con el editor de texto elegido
- [ ] Exista una pagina para mostrar blogs creados

**Comment by SaraUP** [comment]
https://www.todoexpertos.com/preguntas/6q99f6my9wvkwv6p/como-crear-un-editor-de-textos-en-html-y-javascript-que-guarde-el-texto-en-un-txt-en-el-servidor-con-php

**Comment by MarianaCarlo** [comment]
Se terminó el front end de los blogs pero con algunas pequeñas fallas

**Comment by SaraUP** [comment]
No se notan! Casi ya estan!

**Comment by TinCodes** [comment]
El editor esta quedando super igual

**Comment by TinCodes** [comment]
Y listo, era mejor con un editor simple.
