### ISSUE TITLE
Hacer la presentación del proyecto

### ISSUE THREAD

**Issue by camiloayza23** [Dev-Eritas/Dev-Eritas#95]
## User Story

**COMO:** Dev-Eritas 
**QUIERO:** Hacer la presentacion para el fin de curso 
**PARA QUE** Se presente el producto final al docente

## Criterio de Aceptacion
- [ ] Hacer una presentación PowerPoint (_LOS CRITERIOS AUN NO HAN SIDO DADOS_)

**Comment by camiloayza23** [comment]
Contenido de la presentación
  Descripción del proyecto
    Objetivo Principal
    Presupuesto en Sicoes
    Listado de Requerimientos mínimos
  Propuesta
    Mockups
    Arquitectura de Software
      Front-end
      Back-end

Demo de la aplicación
   Crear un usuario
   Flujos y/o casos de uso

Conclusiones

**Comment by SaraUP** [comment]
Chicos ya acabe!!

**Comment by TinCodes** [comment]
Me parece que cubre todo lo necesario, super!
